name: Benchmarks

on:
  pull_request:
    types: [ labeled ]

jobs:
  benchmark:
    if: ${{ github.event.label.name == 'action:run-benchmark' }}
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: install python
       uses: actions/setup-python@v3
       with:
         python-version: 3.10
         cache: 'pip'
     - name: install benchmark requirements
       run: |
         pip install -r benchmarks/benchmark_requirements.txt
     - name: install package from commit
       run: |
        pip install --quiet git+${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git@${GITHUB_SHA}
     - name: deploy stable benchmark VMs
       run: |
        redisbench-admin deploy \
         --inventory_git https://github.com/RedisLabsModules/testing-infrastructure/tree/master/terraform/oss-standalone-redis-small \
         --set_env_vars_json "deploy-env.json" \
         --inventory_local_dir /tmp/env
