name: Benchmarks

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled]

env:
  EC2_PRIVATE_PEM: ${{ secrets.PERFORMANCE_EC2_PRIVATE_PEM }}
  AWS_ACCESS_KEY_ID: ${{ secrets.PERFORMANCE_EC2_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PERFORMANCE_EC2_SECRET_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.PERFORMANCE_EC2_REGION }}

jobs:
  benchmark:
    if: ${{ contains(github.event.*.labels.*.name, 'action:run-benchmark') }}
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: install python
       uses: actions/setup-python@v3
       with:
         python-version: '3.10'
         cache: 'pip'
     - name: install benchmark requirements
       run: |
         pip install -r benchmarks/benchmark_requirements.txt
     - name: install package from commit
       run: |
        pip install --quiet git+${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git@${GITHUB_SHA}
     - name: deploy_vms
       run: |
        redisbench-admin deploy \
         --inventory_git https://github.com/RedisLabsModules/testing-infrastructure/tree/master/terraform/oss-standalone-redis-small \
         --set_env_vars_json "/tmp/deploy-env.json" \
         --inventory_local_dir /tmp/inventory
        CLIENT_PUBLIC_IP=$(/tmp/deploy-env.json | jq '.CLIENT_PUBLIC_IP')
        CLIENT_PRIVATE_IP=$(/tmp/deploy-env.json | jq '.CLIENT_PRIVATE_IP')
        SERVER_PUBLIC_IP=$(/tmp/deploy-env.json | jq '.SERVER_PUBLIC_IP')
        SERVER_PRIVATE_IP=$(/tmp/deploy-env.json | jq '.SERVER_PRIVATE_IP')
        echo "::set-output name=CLIENT_PUBLIC_IP::${CLIENT_PUBLIC_IP}"
        echo "::set-output name=CLIENT_PRIVATE_IP::${CLIENT_PRIVATE_IP}"
        echo "::set-output name=SERVER_PUBLIC_IP::${SERVER_PUBLIC_IP}"
        echo "::set-output name=SERVER_PRIVATE_IP::${SERVER_PRIVATE_IP}"
     - name: Client logic
       run: |
            echo "CLIENT_PUBLIC_IP: ${{steps.deploy_vms.outputs.CLIENT_PUBLIC_IP}}"
            echo "CLIENT_PRIVATE_IP: ${{steps.deploy_vms.outputs.CLIENT_PRIVATE_IP}}"
            echo "SERVER_PUBLIC_IP: ${{steps.deploy_vms.outputs.SERVER_PUBLIC_IP}}"
            echo "SERVER_PRIVATE_IP: ${{steps.deploy_vms.outputs.SERVER_PRIVATE_IP}}"
     - name: destroy_vms
       run: |
        redisbench-admin deploy \
         --inventory_git https://github.com/RedisLabsModules/testing-infrastructure/tree/master/terraform/oss-standalone-redis-small \
         --set_env_vars_json "deploy-env.json" \
         --inventory_local_dir /tmp/inventory \
         --destroy
